author: Elias Woods
database: false
description: plugin for westeroscraft
main: com.westeroscraft.gob.core.CorePlugin
name: GOB
depend: [Citizens]
startup: postworld
version: '0.1'
commands:
    elo:
       description: Shows your elo
       usage: |
            /elo

