author: Elias Woods
database: false
description: plugin to track elo rankings of players
main: com.westeroscraft.gob.honor.HonorPlugin
name: ELOrank
startup: postworld
version: '0.1'
commands:
    elo:
       description: Shows your elo
       usage: |
            /elo

